name: Python checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - uses: py-actions/flake8@v2
        with:
          plugins: flake8-pyproject
  mypy:
    name: Type check with mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Type check with mypy
        uses: py-actions/mypy@v1
        with:
          args: --ignore-missing-imports
      