name: Python checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  flake8:
    name: Lint with Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint with flake8
        uses: py-actions/py-flake8@v1
        with:
          args: --max-line-length=120
  mypy:
    name: Type check with mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Type check with mypy
        uses: py-actions/py-mypy@v1
        with:
          args: --ignore-missing-imports
      